// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: order.sql

package db

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
  owner,
  status,
  delivery_fee,
  subtotal,
  total
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, owner, status, delivery_fee, subtotal, total, created_at
`

type CreateOrderParams struct {
	Owner       string `json:"owner"`
	Status      string `json:"status"`
	DeliveryFee int64  `json:"delivery_fee"`
	Subtotal    int64  `json:"subtotal"`
	Total       int64  `json:"total"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.Owner,
		arg.Status,
		arg.DeliveryFee,
		arg.Subtotal,
		arg.Total,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Status,
		&i.DeliveryFee,
		&i.Subtotal,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders
WHERE id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteOrder, id)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT id, owner, status, delivery_fee, subtotal, total, created_at FROM orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Status,
		&i.DeliveryFee,
		&i.Subtotal,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
SELECT id, owner, status, delivery_fee, subtotal, total, created_at FROM orders
WHERE id = $1 LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetOrderForUpdate(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderForUpdate, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Status,
		&i.DeliveryFee,
		&i.Subtotal,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, owner, status, delivery_fee, subtotal, total, created_at FROM orders
WHERE owner = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListOrdersParams struct {
	Owner  string `json:"owner"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrders, arg.Owner, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Status,
			&i.DeliveryFee,
			&i.Subtotal,
			&i.Total,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE orders
SET status = $2
WHERE id = $1
RETURNING id, owner, status, delivery_fee, subtotal, total, created_at
`

type UpdateOrderParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrder, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Status,
		&i.DeliveryFee,
		&i.Subtotal,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}
